### PR TITLE
added Dockerfile

### PR DESCRIPTION
**Pull request by ddimick**

### CODE REVIEW

**Comment by govizlora** [comment]
Thanks for contributing! I'm pretty new to docker, do you know why you use `git clone` to get the code, instead of using the code inside the repo? I assume it would be faster to use the local file?

**Comment by govizlora** [comment]
Also, what is the use case for this? I see it is using the webpack dev server for the backend

**Comment by ddimick** [comment]
It's for those who want to run the node app inside a Docker container. It uses the official node image as the base image, then git clones your repository into it, and then can be run as a stand-alone instance. because Docker containers are immutable once created, I clone your repository into it so that the docker image can be built in a single step with whatever is current in master.

I know next to nothing about node or yarn, so for me this was the easiest way to fire it up without worrying about host dependencies.

**Comment by ddimick** [comment]
> Why you use `git clone` to get the code, instead of using the code inside the repo? I assume it would be faster to use the local file?

The `git clone` is only run once, when the image is built or updated, but not when the image is started/stopped/restarted.

**Comment by govizlora** [comment]
I see. Since all the code is cloned from github, I think there is no need for the user to clone this repo in order to build the docker image? Can you publish the docker file in a gist or your repo, then I can include the link in the readme? This way, for people who want to try it locally but don't want to use `node` or `yarn`, they can use your dockerfile directly without cloning this repo by themselves.

**Comment by ddimick** [comment]
Sure thing, the gist is at https://gist.github.com/ddimick/d0e82da4805775bb12f2995b20fa223a.

**Comment by govizlora** [comment]
Just added to the readme (https://github.com/govizlora/optical-breacher/commit/9c7f7105c8d3b7f7c2fc78ad33d3a942c3c04292). Thank you!

**Comment by govizlora** [comment]
@all-contributors please add @ddimick for Dockerfile

**Comment by govizlora** [comment]
@all-contributors please add @ddimick for infra

**Pull request closed without merging**
